package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ArchivosSincronizacion generated by hbm2java
 */
public class ArchivosSincronizacion  implements java.io.Serializable {


     private Integer idArchivo;
     private Sucursales sucursales;
     private String nombre;
     private int estado;
     private String pathArchivo;
     private Integer tamano;
     private Date fecha;
     private String md5;
     private Integer noCfds;
     private String idCfdsList;
     private Set cfdses = new HashSet(0);

    public ArchivosSincronizacion() {
    }

	
    public ArchivosSincronizacion(Sucursales sucursales, String nombre, int estado, Date fecha) {
        this.sucursales = sucursales;
        this.nombre = nombre;
        this.estado = estado;
        this.fecha = fecha;
    }
    public ArchivosSincronizacion(Sucursales sucursales, String nombre, int estado, String pathArchivo, Integer tamano, Date fecha, String md5, Integer noCfds, String idCfdsList, Set cfdses) {
       this.sucursales = sucursales;
       this.nombre = nombre;
       this.estado = estado;
       this.pathArchivo = pathArchivo;
       this.tamano = tamano;
       this.fecha = fecha;
       this.md5 = md5;
       this.noCfds = noCfds;
       this.idCfdsList = idCfdsList;
       this.cfdses = cfdses;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getPathArchivo() {
        return this.pathArchivo;
    }
    
    public void setPathArchivo(String pathArchivo) {
        this.pathArchivo = pathArchivo;
    }
    public Integer getTamano() {
        return this.tamano;
    }
    
    public void setTamano(Integer tamano) {
        this.tamano = tamano;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMd5() {
        return this.md5;
    }
    
    public void setMd5(String md5) {
        this.md5 = md5;
    }
    public Integer getNoCfds() {
        return this.noCfds;
    }
    
    public void setNoCfds(Integer noCfds) {
        this.noCfds = noCfds;
    }
    public String getIdCfdsList() {
        return this.idCfdsList;
    }
    
    public void setIdCfdsList(String idCfdsList) {
        this.idCfdsList = idCfdsList;
    }
    public Set getCfdses() {
        return this.cfdses;
    }
    
    public void setCfdses(Set cfdses) {
        this.cfdses = cfdses;
    }




}


