package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoPlantillas generated by hbm2java
 */
public class CatalogoPlantillas  implements java.io.Serializable {


     private Integer idPlantilla;
     private Integer idEmpresa;
     private String nombre;
     private String url;
     private Date fechaAlta;
     private Boolean reload;
     private Boolean base;
     private String textColor;
     private String headerColor;
     private String backColor;
     private Set tiposCfds = new HashSet(0);

    public CatalogoPlantillas() {
    }

	
    public CatalogoPlantillas(String nombre, String url) {
        this.nombre = nombre;
        this.url = url;
    }
    public CatalogoPlantillas(Integer idEmpresa, String nombre, String url, Date fechaAlta, Boolean reload, Boolean base, String textColor, String headerColor, String backColor, Set tiposCfds) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.url = url;
       this.fechaAlta = fechaAlta;
       this.reload = reload;
       this.base = base;
       this.textColor = textColor;
       this.headerColor = headerColor;
       this.backColor = backColor;
       this.tiposCfds = tiposCfds;
    }
   
    public Integer getIdPlantilla() {
        return this.idPlantilla;
    }
    
    public void setIdPlantilla(Integer idPlantilla) {
        this.idPlantilla = idPlantilla;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Boolean getReload() {
        return this.reload;
    }
    
    public void setReload(Boolean reload) {
        this.reload = reload;
    }
    public Boolean getBase() {
        return this.base;
    }
    
    public void setBase(Boolean base) {
        this.base = base;
    }
    public String getTextColor() {
        return this.textColor;
    }
    
    public void setTextColor(String textColor) {
        this.textColor = textColor;
    }
    public String getHeaderColor() {
        return this.headerColor;
    }
    
    public void setHeaderColor(String headerColor) {
        this.headerColor = headerColor;
    }
    public String getBackColor() {
        return this.backColor;
    }
    
    public void setBackColor(String backColor) {
        this.backColor = backColor;
    }
    public Set getTiposCfds() {
        return this.tiposCfds;
    }
    
    public void setTiposCfds(Set tiposCfds) {
        this.tiposCfds = tiposCfds;
    }




}


