package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CertificadosSucursales generated by hbm2java
 */
public class CertificadosSucursales  implements java.io.Serializable {


     private Integer idCertificado;
     private String certificado;
     private Date validode;
     private Date validohasta;
     private String pkey;
     private String passwd;
     private String serie;
     private String estado;
     private Date ultimaVerificacion;
     private Set sucursaleses = new HashSet(0);

    public CertificadosSucursales() {
    }

	
    public CertificadosSucursales(Date validode, Date validohasta, Date ultimaVerificacion) {
        this.validode = validode;
        this.validohasta = validohasta;
        this.ultimaVerificacion = ultimaVerificacion;
    }
    public CertificadosSucursales(String certificado, Date validode, Date validohasta, String pkey, String passwd, String serie, String estado, Date ultimaVerificacion, Set sucursaleses) {
       this.certificado = certificado;
       this.validode = validode;
       this.validohasta = validohasta;
       this.pkey = pkey;
       this.passwd = passwd;
       this.serie = serie;
       this.estado = estado;
       this.ultimaVerificacion = ultimaVerificacion;
       this.sucursaleses = sucursaleses;
    }
   
    public Integer getIdCertificado() {
        return this.idCertificado;
    }
    
    public void setIdCertificado(Integer idCertificado) {
        this.idCertificado = idCertificado;
    }
    public String getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(String certificado) {
        this.certificado = certificado;
    }
    public Date getValidode() {
        return this.validode;
    }
    
    public void setValidode(Date validode) {
        this.validode = validode;
    }
    public Date getValidohasta() {
        return this.validohasta;
    }
    
    public void setValidohasta(Date validohasta) {
        this.validohasta = validohasta;
    }
    public String getPkey() {
        return this.pkey;
    }
    
    public void setPkey(String pkey) {
        this.pkey = pkey;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getUltimaVerificacion() {
        return this.ultimaVerificacion;
    }
    
    public void setUltimaVerificacion(Date ultimaVerificacion) {
        this.ultimaVerificacion = ultimaVerificacion;
    }
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }




}


