package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ConectorAdaptador generated by hbm2java
 */
public class ConectorAdaptador  implements java.io.Serializable {


     private Integer idConectorAdaptador;
     private Integer idEmpresa;
     private String nombre;
     private String descripcion;
     private String stylusConector;
     private String xsltToTralix;
     private String estado;
     private Set tiposCfds = new HashSet(0);

    public ConectorAdaptador() {
    }

	
    public ConectorAdaptador(String nombre) {
        this.nombre = nombre;
    }
    public ConectorAdaptador(Integer idEmpresa, String nombre, String descripcion, String stylusConector, String xsltToTralix, String estado, Set tiposCfds) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.stylusConector = stylusConector;
       this.xsltToTralix = xsltToTralix;
       this.estado = estado;
       this.tiposCfds = tiposCfds;
    }
   
    public Integer getIdConectorAdaptador() {
        return this.idConectorAdaptador;
    }
    
    public void setIdConectorAdaptador(Integer idConectorAdaptador) {
        this.idConectorAdaptador = idConectorAdaptador;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getStylusConector() {
        return this.stylusConector;
    }
    
    public void setStylusConector(String stylusConector) {
        this.stylusConector = stylusConector;
    }
    public String getXsltToTralix() {
        return this.xsltToTralix;
    }
    
    public void setXsltToTralix(String xsltToTralix) {
        this.xsltToTralix = xsltToTralix;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getTiposCfds() {
        return this.tiposCfds;
    }
    
    public void setTiposCfds(Set tiposCfds) {
        this.tiposCfds = tiposCfds;
    }




}


