package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ConfiguracionLayout generated by hbm2java
 */
public class ConfiguracionLayout  implements java.io.Serializable {


     private Integer idLayout;
     private int idEmpresa;
     private String nombre;
     private String json;
     private Set usuariosRecepcions = new HashSet(0);

    public ConfiguracionLayout() {
    }

	
    public ConfiguracionLayout(int idEmpresa, String nombre, String json) {
        this.idEmpresa = idEmpresa;
        this.nombre = nombre;
        this.json = json;
    }
    public ConfiguracionLayout(int idEmpresa, String nombre, String json, Set usuariosRecepcions) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.json = json;
       this.usuariosRecepcions = usuariosRecepcions;
    }
   
    public Integer getIdLayout() {
        return this.idLayout;
    }
    
    public void setIdLayout(Integer idLayout) {
        this.idLayout = idLayout;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getJson() {
        return this.json;
    }
    
    public void setJson(String json) {
        this.json = json;
    }
    public Set getUsuariosRecepcions() {
        return this.usuariosRecepcions;
    }
    
    public void setUsuariosRecepcions(Set usuariosRecepcions) {
        this.usuariosRecepcions = usuariosRecepcions;
    }




}


