package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CustomerKeys generated by hbm2java
 */
public class CustomerKeys  implements java.io.Serializable {


     private Integer idCustomerkey;
     private String nombre;
     private String customerKey;
     private String email;
     private String estadoTimbrado;
     private Set empresases = new HashSet(0);

    public CustomerKeys() {
    }

	
    public CustomerKeys(String customerKey, String estadoTimbrado) {
        this.customerKey = customerKey;
        this.estadoTimbrado = estadoTimbrado;
    }
    public CustomerKeys(String nombre, String customerKey, String email, String estadoTimbrado, Set empresases) {
       this.nombre = nombre;
       this.customerKey = customerKey;
       this.email = email;
       this.estadoTimbrado = estadoTimbrado;
       this.empresases = empresases;
    }
   
    public Integer getIdCustomerkey() {
        return this.idCustomerkey;
    }
    
    public void setIdCustomerkey(Integer idCustomerkey) {
        this.idCustomerkey = idCustomerkey;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCustomerKey() {
        return this.customerKey;
    }
    
    public void setCustomerKey(String customerKey) {
        this.customerKey = customerKey;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEstadoTimbrado() {
        return this.estadoTimbrado;
    }
    
    public void setEstadoTimbrado(String estadoTimbrado) {
        this.estadoTimbrado = estadoTimbrado;
    }
    public Set getEmpresases() {
        return this.empresases;
    }
    
    public void setEmpresases(Set empresases) {
        this.empresases = empresases;
    }




}


