package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentosRecibidos generated by hbm2java
 */
public class DocumentosRecibidos  implements java.io.Serializable {


     private Integer idArchivo;
     private Sucursales sucursales;
     private TiposCfd tiposCfd;
     private Integer idCfd;
     private Long identificador;
     private String cliente;
     private Date fechaRecepcion;
     private String archivo;
     private String estado;
     private String tipo;
     private String nombre;
     private String error;
     private Boolean reportado;
     private int idGenerator;
     private boolean hugeFile;
     private Integer idMetadata;
     private String columna0;
     private String columna1;
     private String columna2;
     private String columna3;
     private String columna4;
     private String columna5;
     private String columna6;
     private String columna7;
     private String columna8;
     private String columna9;
     private String columna10;
     private String columna11;
     private String columna12;
     private String columna13;
     private String columna14;
     private String columna15;
     private String columna16;
     private String columna17;
     private String columna18;
     private String columna19;
     private Set erroresGeneracions = new HashSet(0);

    public DocumentosRecibidos() {
    }

	
    public DocumentosRecibidos(Sucursales sucursales, TiposCfd tiposCfd, Date fechaRecepcion, String archivo, int idGenerator, boolean hugeFile) {
        this.sucursales = sucursales;
        this.tiposCfd = tiposCfd;
        this.fechaRecepcion = fechaRecepcion;
        this.archivo = archivo;
        this.idGenerator = idGenerator;
        this.hugeFile = hugeFile;
    }
    public DocumentosRecibidos(Sucursales sucursales, TiposCfd tiposCfd, Integer idCfd, Long identificador, String cliente, Date fechaRecepcion, String archivo, String estado, String tipo, String nombre, String error, Boolean reportado, int idGenerator, boolean hugeFile, Integer idMetadata, String columna0, String columna1, String columna2, String columna3, String columna4, String columna5, String columna6, String columna7, String columna8, String columna9, String columna10, String columna11, String columna12, String columna13, String columna14, String columna15, String columna16, String columna17, String columna18, String columna19, Set erroresGeneracions) {
       this.sucursales = sucursales;
       this.tiposCfd = tiposCfd;
       this.idCfd = idCfd;
       this.identificador = identificador;
       this.cliente = cliente;
       this.fechaRecepcion = fechaRecepcion;
       this.archivo = archivo;
       this.estado = estado;
       this.tipo = tipo;
       this.nombre = nombre;
       this.error = error;
       this.reportado = reportado;
       this.idGenerator = idGenerator;
       this.hugeFile = hugeFile;
       this.idMetadata = idMetadata;
       this.columna0 = columna0;
       this.columna1 = columna1;
       this.columna2 = columna2;
       this.columna3 = columna3;
       this.columna4 = columna4;
       this.columna5 = columna5;
       this.columna6 = columna6;
       this.columna7 = columna7;
       this.columna8 = columna8;
       this.columna9 = columna9;
       this.columna10 = columna10;
       this.columna11 = columna11;
       this.columna12 = columna12;
       this.columna13 = columna13;
       this.columna14 = columna14;
       this.columna15 = columna15;
       this.columna16 = columna16;
       this.columna17 = columna17;
       this.columna18 = columna18;
       this.columna19 = columna19;
       this.erroresGeneracions = erroresGeneracions;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public Integer getIdCfd() {
        return this.idCfd;
    }
    
    public void setIdCfd(Integer idCfd) {
        this.idCfd = idCfd;
    }
    public Long getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(Long identificador) {
        this.identificador = identificador;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    public Boolean getReportado() {
        return this.reportado;
    }
    
    public void setReportado(Boolean reportado) {
        this.reportado = reportado;
    }
    public int getIdGenerator() {
        return this.idGenerator;
    }
    
    public void setIdGenerator(int idGenerator) {
        this.idGenerator = idGenerator;
    }
    public boolean isHugeFile() {
        return this.hugeFile;
    }
    
    public void setHugeFile(boolean hugeFile) {
        this.hugeFile = hugeFile;
    }
    public Integer getIdMetadata() {
        return this.idMetadata;
    }
    
    public void setIdMetadata(Integer idMetadata) {
        this.idMetadata = idMetadata;
    }
    public String getColumna0() {
        return this.columna0;
    }
    
    public void setColumna0(String columna0) {
        this.columna0 = columna0;
    }
    public String getColumna1() {
        return this.columna1;
    }
    
    public void setColumna1(String columna1) {
        this.columna1 = columna1;
    }
    public String getColumna2() {
        return this.columna2;
    }
    
    public void setColumna2(String columna2) {
        this.columna2 = columna2;
    }
    public String getColumna3() {
        return this.columna3;
    }
    
    public void setColumna3(String columna3) {
        this.columna3 = columna3;
    }
    public String getColumna4() {
        return this.columna4;
    }
    
    public void setColumna4(String columna4) {
        this.columna4 = columna4;
    }
    public String getColumna5() {
        return this.columna5;
    }
    
    public void setColumna5(String columna5) {
        this.columna5 = columna5;
    }
    public String getColumna6() {
        return this.columna6;
    }
    
    public void setColumna6(String columna6) {
        this.columna6 = columna6;
    }
    public String getColumna7() {
        return this.columna7;
    }
    
    public void setColumna7(String columna7) {
        this.columna7 = columna7;
    }
    public String getColumna8() {
        return this.columna8;
    }
    
    public void setColumna8(String columna8) {
        this.columna8 = columna8;
    }
    public String getColumna9() {
        return this.columna9;
    }
    
    public void setColumna9(String columna9) {
        this.columna9 = columna9;
    }
    public String getColumna10() {
        return this.columna10;
    }
    
    public void setColumna10(String columna10) {
        this.columna10 = columna10;
    }
    public String getColumna11() {
        return this.columna11;
    }
    
    public void setColumna11(String columna11) {
        this.columna11 = columna11;
    }
    public String getColumna12() {
        return this.columna12;
    }
    
    public void setColumna12(String columna12) {
        this.columna12 = columna12;
    }
    public String getColumna13() {
        return this.columna13;
    }
    
    public void setColumna13(String columna13) {
        this.columna13 = columna13;
    }
    public String getColumna14() {
        return this.columna14;
    }
    
    public void setColumna14(String columna14) {
        this.columna14 = columna14;
    }
    public String getColumna15() {
        return this.columna15;
    }
    
    public void setColumna15(String columna15) {
        this.columna15 = columna15;
    }
    public String getColumna16() {
        return this.columna16;
    }
    
    public void setColumna16(String columna16) {
        this.columna16 = columna16;
    }
    public String getColumna17() {
        return this.columna17;
    }
    
    public void setColumna17(String columna17) {
        this.columna17 = columna17;
    }
    public String getColumna18() {
        return this.columna18;
    }
    
    public void setColumna18(String columna18) {
        this.columna18 = columna18;
    }
    public String getColumna19() {
        return this.columna19;
    }
    
    public void setColumna19(String columna19) {
        this.columna19 = columna19;
    }
    public Set getErroresGeneracions() {
        return this.erroresGeneracions;
    }
    
    public void setErroresGeneracions(Set erroresGeneracions) {
        this.erroresGeneracions = erroresGeneracions;
    }




}


