package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer idEmpresa;
     private CustomerKeys customerKeys;
     private String nombre;
     private String rfc;
     private String calle;
     private String numExterior;
     private String numInterior;
     private String colonia;
     private String localidad;
     private String referencia;
     private String municipio;
     private String estado;
     private String pais;
     private String cp;
     private Boolean multiCertificado;
     private Boolean multiXslt;
     private String codigogln;
     private Boolean onlyReception;
     private String status;
     private String keyEmpresa;
     private String email;
     private String telefono;
     private String curp;
     private Byte tieneAddenda;
     private Byte esFrontera;
     private String nombreArchivoLogo;
     private String paginaWeb;
     private boolean isBorder;
     private String cfdVersion;
     private String nombreContacto;
     private Set sucursaleses = new HashSet(0);
     private Set clienteses = new HashSet(0);
     private Set tiposCfds = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(String nombre, String rfc, String calle, String municipio, String estado, String pais, String cp, String status, boolean isBorder, String cfdVersion) {
        this.nombre = nombre;
        this.rfc = rfc;
        this.calle = calle;
        this.municipio = municipio;
        this.estado = estado;
        this.pais = pais;
        this.cp = cp;
        this.status = status;
        this.isBorder = isBorder;
        this.cfdVersion = cfdVersion;
    }
    public Empresas(CustomerKeys customerKeys, String nombre, String rfc, String calle, String numExterior, String numInterior, String colonia, String localidad, String referencia, String municipio, String estado, String pais, String cp, Boolean multiCertificado, Boolean multiXslt, String codigogln, Boolean onlyReception, String status, String keyEmpresa, String email, String telefono, String curp, Byte tieneAddenda, Byte esFrontera, String nombreArchivoLogo, String paginaWeb, boolean isBorder, String cfdVersion, String nombreContacto, Set sucursaleses, Set clienteses, Set tiposCfds) {
       this.customerKeys = customerKeys;
       this.nombre = nombre;
       this.rfc = rfc;
       this.calle = calle;
       this.numExterior = numExterior;
       this.numInterior = numInterior;
       this.colonia = colonia;
       this.localidad = localidad;
       this.referencia = referencia;
       this.municipio = municipio;
       this.estado = estado;
       this.pais = pais;
       this.cp = cp;
       this.multiCertificado = multiCertificado;
       this.multiXslt = multiXslt;
       this.codigogln = codigogln;
       this.onlyReception = onlyReception;
       this.status = status;
       this.keyEmpresa = keyEmpresa;
       this.email = email;
       this.telefono = telefono;
       this.curp = curp;
       this.tieneAddenda = tieneAddenda;
       this.esFrontera = esFrontera;
       this.nombreArchivoLogo = nombreArchivoLogo;
       this.paginaWeb = paginaWeb;
       this.isBorder = isBorder;
       this.cfdVersion = cfdVersion;
       this.nombreContacto = nombreContacto;
       this.sucursaleses = sucursaleses;
       this.clienteses = clienteses;
       this.tiposCfds = tiposCfds;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public CustomerKeys getCustomerKeys() {
        return this.customerKeys;
    }
    
    public void setCustomerKeys(CustomerKeys customerKeys) {
        this.customerKeys = customerKeys;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumExterior() {
        return this.numExterior;
    }
    
    public void setNumExterior(String numExterior) {
        this.numExterior = numExterior;
    }
    public String getNumInterior() {
        return this.numInterior;
    }
    
    public void setNumInterior(String numInterior) {
        this.numInterior = numInterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Boolean getMultiCertificado() {
        return this.multiCertificado;
    }
    
    public void setMultiCertificado(Boolean multiCertificado) {
        this.multiCertificado = multiCertificado;
    }
    public Boolean getMultiXslt() {
        return this.multiXslt;
    }
    
    public void setMultiXslt(Boolean multiXslt) {
        this.multiXslt = multiXslt;
    }
    public String getCodigogln() {
        return this.codigogln;
    }
    
    public void setCodigogln(String codigogln) {
        this.codigogln = codigogln;
    }
    public Boolean getOnlyReception() {
        return this.onlyReception;
    }
    
    public void setOnlyReception(Boolean onlyReception) {
        this.onlyReception = onlyReception;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getKeyEmpresa() {
        return this.keyEmpresa;
    }
    
    public void setKeyEmpresa(String keyEmpresa) {
        this.keyEmpresa = keyEmpresa;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public Byte getTieneAddenda() {
        return this.tieneAddenda;
    }
    
    public void setTieneAddenda(Byte tieneAddenda) {
        this.tieneAddenda = tieneAddenda;
    }
    public Byte getEsFrontera() {
        return this.esFrontera;
    }
    
    public void setEsFrontera(Byte esFrontera) {
        this.esFrontera = esFrontera;
    }
    public String getNombreArchivoLogo() {
        return this.nombreArchivoLogo;
    }
    
    public void setNombreArchivoLogo(String nombreArchivoLogo) {
        this.nombreArchivoLogo = nombreArchivoLogo;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public boolean isIsBorder() {
        return this.isBorder;
    }
    
    public void setIsBorder(boolean isBorder) {
        this.isBorder = isBorder;
    }
    public String getCfdVersion() {
        return this.cfdVersion;
    }
    
    public void setCfdVersion(String cfdVersion) {
        this.cfdVersion = cfdVersion;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }
    public Set getTiposCfds() {
        return this.tiposCfds;
    }
    
    public void setTiposCfds(Set tiposCfds) {
        this.tiposCfds = tiposCfds;
    }




}


