package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA



/**
 * ErroresGeneracion generated by hbm2java
 */
public class ErroresGeneracion  implements java.io.Serializable {


     private Integer idError;
     private DocumentosRecibidos documentosRecibidos;
     private String pathXml;
     private String descripcionXml;
     private String valorEncontrado;
     private String error;

    public ErroresGeneracion() {
    }

	
    public ErroresGeneracion(DocumentosRecibidos documentosRecibidos, String pathXml, String descripcionXml, String error) {
        this.documentosRecibidos = documentosRecibidos;
        this.pathXml = pathXml;
        this.descripcionXml = descripcionXml;
        this.error = error;
    }
    public ErroresGeneracion(DocumentosRecibidos documentosRecibidos, String pathXml, String descripcionXml, String valorEncontrado, String error) {
       this.documentosRecibidos = documentosRecibidos;
       this.pathXml = pathXml;
       this.descripcionXml = descripcionXml;
       this.valorEncontrado = valorEncontrado;
       this.error = error;
    }
   
    public Integer getIdError() {
        return this.idError;
    }
    
    public void setIdError(Integer idError) {
        this.idError = idError;
    }
    public DocumentosRecibidos getDocumentosRecibidos() {
        return this.documentosRecibidos;
    }
    
    public void setDocumentosRecibidos(DocumentosRecibidos documentosRecibidos) {
        this.documentosRecibidos = documentosRecibidos;
    }
    public String getPathXml() {
        return this.pathXml;
    }
    
    public void setPathXml(String pathXml) {
        this.pathXml = pathXml;
    }
    public String getDescripcionXml() {
        return this.descripcionXml;
    }
    
    public void setDescripcionXml(String descripcionXml) {
        this.descripcionXml = descripcionXml;
    }
    public String getValorEncontrado() {
        return this.valorEncontrado;
    }
    
    public void setValorEncontrado(String valorEncontrado) {
        this.valorEncontrado = valorEncontrado;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }




}


