package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private Integer idSucursal;
     private Empresas empresas;
     private CertificadosSucursales certificadosSucursales;
     private String nombre;
     private String calle;
     private String numExterior;
     private String numInterior;
     private String colonia;
     private String localidad;
     private String referencia;
     private String municipio;
     private String estado;
     private String pais;
     private String cp;
     private String tiposucursal;
     private String codigogln;
     private String claveSucursal;
     private String extras;
     private Boolean printWhenSend;
     private String email;
     private String telefono;
     private boolean esFrontera;
     private String lugarExpedicion;
     private Set archivosSincronizacions = new HashSet(0);
     private Set cfdsesForIdSucursal = new HashSet(0);
     private Set cfdsesForImprimirEn = new HashSet(0);
     private Set documentosRecibidoses = new HashSet(0);
     private Set usuariosRecepcions = new HashSet(0);

    public Sucursales() {
    }

	
    public Sucursales(Empresas empresas, String nombre, String pais, String tiposucursal, boolean esFrontera) {
        this.empresas = empresas;
        this.nombre = nombre;
        this.pais = pais;
        this.tiposucursal = tiposucursal;
        this.esFrontera = esFrontera;
    }
    public Sucursales(Empresas empresas, CertificadosSucursales certificadosSucursales, String nombre, String calle, String numExterior, String numInterior, String colonia, String localidad, String referencia, String municipio, String estado, String pais, String cp, String tiposucursal, String codigogln, String claveSucursal, String extras, Boolean printWhenSend, String email, String telefono, boolean esFrontera, String lugarExpedicion, Set archivosSincronizacions, Set cfdsesForIdSucursal, Set cfdsesForImprimirEn, Set documentosRecibidoses, Set usuariosRecepcions) {
       this.empresas = empresas;
       this.certificadosSucursales = certificadosSucursales;
       this.nombre = nombre;
       this.calle = calle;
       this.numExterior = numExterior;
       this.numInterior = numInterior;
       this.colonia = colonia;
       this.localidad = localidad;
       this.referencia = referencia;
       this.municipio = municipio;
       this.estado = estado;
       this.pais = pais;
       this.cp = cp;
       this.tiposucursal = tiposucursal;
       this.codigogln = codigogln;
       this.claveSucursal = claveSucursal;
       this.extras = extras;
       this.printWhenSend = printWhenSend;
       this.email = email;
       this.telefono = telefono;
       this.esFrontera = esFrontera;
       this.lugarExpedicion = lugarExpedicion;
       this.archivosSincronizacions = archivosSincronizacions;
       this.cfdsesForIdSucursal = cfdsesForIdSucursal;
       this.cfdsesForImprimirEn = cfdsesForImprimirEn;
       this.documentosRecibidoses = documentosRecibidoses;
       this.usuariosRecepcions = usuariosRecepcions;
    }
   
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public CertificadosSucursales getCertificadosSucursales() {
        return this.certificadosSucursales;
    }
    
    public void setCertificadosSucursales(CertificadosSucursales certificadosSucursales) {
        this.certificadosSucursales = certificadosSucursales;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumExterior() {
        return this.numExterior;
    }
    
    public void setNumExterior(String numExterior) {
        this.numExterior = numExterior;
    }
    public String getNumInterior() {
        return this.numInterior;
    }
    
    public void setNumInterior(String numInterior) {
        this.numInterior = numInterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getTiposucursal() {
        return this.tiposucursal;
    }
    
    public void setTiposucursal(String tiposucursal) {
        this.tiposucursal = tiposucursal;
    }
    public String getCodigogln() {
        return this.codigogln;
    }
    
    public void setCodigogln(String codigogln) {
        this.codigogln = codigogln;
    }
    public String getClaveSucursal() {
        return this.claveSucursal;
    }
    
    public void setClaveSucursal(String claveSucursal) {
        this.claveSucursal = claveSucursal;
    }
    public String getExtras() {
        return this.extras;
    }
    
    public void setExtras(String extras) {
        this.extras = extras;
    }
    public Boolean getPrintWhenSend() {
        return this.printWhenSend;
    }
    
    public void setPrintWhenSend(Boolean printWhenSend) {
        this.printWhenSend = printWhenSend;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public boolean isEsFrontera() {
        return this.esFrontera;
    }
    
    public void setEsFrontera(boolean esFrontera) {
        this.esFrontera = esFrontera;
    }
    public String getLugarExpedicion() {
        return this.lugarExpedicion;
    }
    
    public void setLugarExpedicion(String lugarExpedicion) {
        this.lugarExpedicion = lugarExpedicion;
    }
    public Set getArchivosSincronizacions() {
        return this.archivosSincronizacions;
    }
    
    public void setArchivosSincronizacions(Set archivosSincronizacions) {
        this.archivosSincronizacions = archivosSincronizacions;
    }
    public Set getCfdsesForIdSucursal() {
        return this.cfdsesForIdSucursal;
    }
    
    public void setCfdsesForIdSucursal(Set cfdsesForIdSucursal) {
        this.cfdsesForIdSucursal = cfdsesForIdSucursal;
    }
    public Set getCfdsesForImprimirEn() {
        return this.cfdsesForImprimirEn;
    }
    
    public void setCfdsesForImprimirEn(Set cfdsesForImprimirEn) {
        this.cfdsesForImprimirEn = cfdsesForImprimirEn;
    }
    public Set getDocumentosRecibidoses() {
        return this.documentosRecibidoses;
    }
    
    public void setDocumentosRecibidoses(Set documentosRecibidoses) {
        this.documentosRecibidoses = documentosRecibidoses;
    }
    public Set getUsuariosRecepcions() {
        return this.usuariosRecepcions;
    }
    
    public void setUsuariosRecepcions(Set usuariosRecepcions) {
        this.usuariosRecepcions = usuariosRecepcions;
    }




}


