package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposCfd generated by hbm2java
 */
public class TiposCfd  implements java.io.Serializable {


     private Integer idTipocfd;
     private ConectorAdaptador conectorAdaptador;
     private Empresas empresas;
     private CatalogoPlantillas catalogoPlantillas;
     private String nombre;
     private String tipo;
     private String stylusConector;
     private String xsltToTralix;
     private boolean modoManual;
     private boolean reload;
     private String encoding;
     private String modo;
     private String tipoUso;
     private Set cfdses = new HashSet(0);
     private Set documentosRecibidoses = new HashSet(0);
     private Set usuariosRecepcions = new HashSet(0);

    public TiposCfd() {
    }

	
    public TiposCfd(Empresas empresas, String tipo, boolean modoManual, boolean reload, String tipoUso) {
        this.empresas = empresas;
        this.tipo = tipo;
        this.modoManual = modoManual;
        this.reload = reload;
        this.tipoUso = tipoUso;
    }
    public TiposCfd(ConectorAdaptador conectorAdaptador, Empresas empresas, CatalogoPlantillas catalogoPlantillas, String nombre, String tipo, String stylusConector, String xsltToTralix, boolean modoManual, boolean reload, String encoding, String modo, String tipoUso, Set cfdses, Set documentosRecibidoses, Set usuariosRecepcions) {
       this.conectorAdaptador = conectorAdaptador;
       this.empresas = empresas;
       this.catalogoPlantillas = catalogoPlantillas;
       this.nombre = nombre;
       this.tipo = tipo;
       this.stylusConector = stylusConector;
       this.xsltToTralix = xsltToTralix;
       this.modoManual = modoManual;
       this.reload = reload;
       this.encoding = encoding;
       this.modo = modo;
       this.tipoUso = tipoUso;
       this.cfdses = cfdses;
       this.documentosRecibidoses = documentosRecibidoses;
       this.usuariosRecepcions = usuariosRecepcions;
    }
   
    public Integer getIdTipocfd() {
        return this.idTipocfd;
    }
    
    public void setIdTipocfd(Integer idTipocfd) {
        this.idTipocfd = idTipocfd;
    }
    public ConectorAdaptador getConectorAdaptador() {
        return this.conectorAdaptador;
    }
    
    public void setConectorAdaptador(ConectorAdaptador conectorAdaptador) {
        this.conectorAdaptador = conectorAdaptador;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public CatalogoPlantillas getCatalogoPlantillas() {
        return this.catalogoPlantillas;
    }
    
    public void setCatalogoPlantillas(CatalogoPlantillas catalogoPlantillas) {
        this.catalogoPlantillas = catalogoPlantillas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getStylusConector() {
        return this.stylusConector;
    }
    
    public void setStylusConector(String stylusConector) {
        this.stylusConector = stylusConector;
    }
    public String getXsltToTralix() {
        return this.xsltToTralix;
    }
    
    public void setXsltToTralix(String xsltToTralix) {
        this.xsltToTralix = xsltToTralix;
    }
    public boolean isModoManual() {
        return this.modoManual;
    }
    
    public void setModoManual(boolean modoManual) {
        this.modoManual = modoManual;
    }
    public boolean isReload() {
        return this.reload;
    }
    
    public void setReload(boolean reload) {
        this.reload = reload;
    }
    public String getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }
    public String getModo() {
        return this.modo;
    }
    
    public void setModo(String modo) {
        this.modo = modo;
    }
    public String getTipoUso() {
        return this.tipoUso;
    }
    
    public void setTipoUso(String tipoUso) {
        this.tipoUso = tipoUso;
    }
    public Set getCfdses() {
        return this.cfdses;
    }
    
    public void setCfdses(Set cfdses) {
        this.cfdses = cfdses;
    }
    public Set getDocumentosRecibidoses() {
        return this.documentosRecibidoses;
    }
    
    public void setDocumentosRecibidoses(Set documentosRecibidoses) {
        this.documentosRecibidoses = documentosRecibidoses;
    }
    public Set getUsuariosRecepcions() {
        return this.usuariosRecepcions;
    }
    
    public void setUsuariosRecepcions(Set usuariosRecepcions) {
        this.usuariosRecepcions = usuariosRecepcions;
    }




}


