package com.iqtb.POJOs;
// Generated 3/02/2016 11:11:30 AM by Hibernate Tools 3.2.1.GA



/**
 * UsuariosRecepcion generated by hbm2java
 */
public class UsuariosRecepcion  implements java.io.Serializable {


     private Integer idUsuario;
     private Sucursales sucursales;
     private TiposCfd tiposCfd;
     private ConfiguracionLayout configuracionLayout;
     private String nombre;
     private String usuario;
     private String passwd;
     private Integer idTipoedi;
     private Boolean istipoedi;
     private String homeftp;
     private String homesftp;

    public UsuariosRecepcion() {
    }

	
    public UsuariosRecepcion(Sucursales sucursales, String nombre, String usuario, String passwd) {
        this.sucursales = sucursales;
        this.nombre = nombre;
        this.usuario = usuario;
        this.passwd = passwd;
    }
    public UsuariosRecepcion(Sucursales sucursales, TiposCfd tiposCfd, ConfiguracionLayout configuracionLayout, String nombre, String usuario, String passwd, Integer idTipoedi, Boolean istipoedi, String homeftp, String homesftp) {
       this.sucursales = sucursales;
       this.tiposCfd = tiposCfd;
       this.configuracionLayout = configuracionLayout;
       this.nombre = nombre;
       this.usuario = usuario;
       this.passwd = passwd;
       this.idTipoedi = idTipoedi;
       this.istipoedi = istipoedi;
       this.homeftp = homeftp;
       this.homesftp = homesftp;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public ConfiguracionLayout getConfiguracionLayout() {
        return this.configuracionLayout;
    }
    
    public void setConfiguracionLayout(ConfiguracionLayout configuracionLayout) {
        this.configuracionLayout = configuracionLayout;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Integer getIdTipoedi() {
        return this.idTipoedi;
    }
    
    public void setIdTipoedi(Integer idTipoedi) {
        this.idTipoedi = idTipoedi;
    }
    public Boolean getIstipoedi() {
        return this.istipoedi;
    }
    
    public void setIstipoedi(Boolean istipoedi) {
        this.istipoedi = istipoedi;
    }
    public String getHomeftp() {
        return this.homeftp;
    }
    
    public void setHomeftp(String homeftp) {
        this.homeftp = homeftp;
    }
    public String getHomesftp() {
        return this.homesftp;
    }
    
    public void setHomesftp(String homesftp) {
        this.homesftp = homesftp;
    }




}


