package com.iqtb.POJOs;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * Xmls generated by hbm2java
 */
public class Xmls  implements java.io.Serializable {


     private int idCfd;
     private Cfds cfds;
     private String xmlTralix;
     private String xmlSat;

    public Xmls() {
    }

	
    public Xmls(int idCfd, Cfds cfds) {
        this.idCfd = idCfd;
        this.cfds = cfds;
    }
    public Xmls(int idCfd, Cfds cfds, String xmlTralix, String xmlSat) {
       this.idCfd = idCfd;
       this.cfds = cfds;
       this.xmlTralix = xmlTralix;
       this.xmlSat = xmlSat;
    }
   
    public int getIdCfd() {
        return this.idCfd;
    }
    
    public void setIdCfd(int idCfd) {
        this.idCfd = idCfd;
    }
    public Cfds getCfds() {
        return this.cfds;
    }
    
    public void setCfds(Cfds cfds) {
        this.cfds = cfds;
    }
    public String getXmlTralix() {
        return this.xmlTralix;
    }
    
    public void setXmlTralix(String xmlTralix) {
        this.xmlTralix = xmlTralix;
    }
    public String getXmlSat() {
        return this.xmlSat;
    }
    
    public void setXmlSat(String xmlSat) {
        this.xmlSat = xmlSat;
    }




}


